
server.port=2222
server.max-http-header-size=400000

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=mbc
spring.datasource.password=1234

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JPA
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database=oracle

# ? pom.xml ? ???? ????? community dialect ?? ?? (??? ?? ?? ??)
# spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.OracleLegacyDialect

# (LOB ?? ?? - ?? ?? ??)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=C:/SpringBoot/movie

# Error
server.error.include-message=always
server.error.include-binding-errors=always